### ISSUE TITLE
[suggestion] allow permanent logged in UUIDs in config

### ISSUE THREAD

**Issue by V-lpen** [Minenash/OpLock#2]
Love this mod, makes playing on my server a lot more fair! thanks for making it. Id love if i could keep certain UUIDs logged in unless explicitly logged out.

**Comment by Minenash** [comment]
Interesting. I could add an auto-login part

**Comment by Rozbiynk** [comment]
this isnt uuid for auto login, right?
![изображение](https://github.com/user-attachments/assets/529e07a1-8cb1-4c09-836f-0f9fa8a34161)

**Comment by Minenash** [comment]
Right, that's a list of people that can have op (since the op file is no longer reliable

**Comment by Rozbiynk** [comment]
also, there is way to send packets that player is op but dont allow them to do use command/certain things? i have problem with tweakermore mod. It uses protocol for seeing comparator signal but only for ops, so i dont see it when "oplock logout". Is there any way to fix that, or it better o open another issue just with this incompability?

**Comment by Minenash** [comment]
@Rozbiynk It's not really an incompatibility, or that. oplock was meant to enable op powers entirely. I'm not sure I want to try to make this mod pick and choose exactly which op powers a person can have

**Comment by Rozbiynk** [comment]
I fix my issue with carpet rule, so its okay

**Comment by Minenash** [comment]
Added in v1.1.0!
